services:
  stormcellar:
    image: stormcellar
    container_name: stormcellar
    environment:
      - OPENWEATHER_API_KEY=7374d2eb287d748d75910813c8cfbdf3
      - LAT=-40.7484
      - LON=-73.9967
      - MQTT_BROKER=10.10.10.10
      - MQTT_PORT=1883
      - MQTT_TOPIC=weather/data
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - test-network
networks:
  test-network:
    driver: bridge