services:
  stormcellar:
    image: ghcr.io/mrfoureyed/stormcellar:latest
    container_name: stormcellar
    environment:
      - OPENWEATHER_API_KEY=null
      - LAT=-40.7484
      - LON=-73.9967
      - MQTT_BROKER=localhost
      - MQTT_PORT=1883
      - MQTT_TOPIC=weather/data
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - test-network
networks:
  test-network:
    driver: bridge